/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.CitaDAO;
import controlador.PacienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelo.Cita;
import modelo.Paciente;

/**
 *
 * @author josesanchez
 */
public class DialogAnadirCita extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAnadirCita.class.getName());

    private List<Paciente> listaPacientes;
    /**
     * Creates new form DialogAnadirCita
     */
    public DialogAnadirCita(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        setSize(400, 320);
        setResizable(false);
        setLocationRelativeTo(parent); 
        cargarPacientes();

        try {

            MaskFormatter maskFecha = new MaskFormatter("##-##-####");

            maskFecha.setPlaceholderCharacter('0');

            jFormattedTextField1.setFormatterFactory(

                    new javax.swing.text.DefaultFormatterFactory(maskFecha));

        } catch (Exception e) {

            e.printStackTrace();

        }

    }
    private void cargarPacientes() {

        PacienteDAO pacienteDAO = new PacienteDAO();

        listaPacientes = pacienteDAO.obtenerTodos();

        jComboBox1.removeAllItems();

        for (Paciente paciente : listaPacientes) {

            jComboBox1.addItem(
                paciente.getIdPaciente()
                + " - "
                + paciente.getNombre()
                + " "
                + paciente.getApellido()
            );

        }

        pacienteDAO.cerrarConexion();

    }
    
    
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 320));
        getContentPane().setLayout(null);

        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 70, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 33, 260, 30);

        jLabel2.setText("Fecha de la cita ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 97, 17);

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(140, 80, 210, 30);

        jLabel3.setText("Hora cita");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 80, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(90, 130, 70, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(180, 130, 70, 23);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a.m.", "p.m." }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(270, 130, 80, 23);

        jLabel4.setText("Num Habitación");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 110, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "216", "217", "218", "219", "220", "221", "222", "223", "224", "225", "226", "227", "228", "229", "230", "231", "232", "233", "234", "235", "236", "237", "238", "239", "240", "241", "242", "243", "244", "245", "246", "247", "248", "249", "250" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(130, 170, 220, 23);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 220, 290, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {

            int indicePaciente = jComboBox1.getSelectedIndex();

            if (indicePaciente < 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Seleccione un paciente.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );

                return;

            }

            Paciente paciente = listaPacientes.get(indicePaciente);

            int idPaciente = paciente.getIdPaciente();

            int idMedico = paciente.getIdMedico();

            String fechaCita = jFormattedTextField1.getText().trim();

            String horaCita =
                    jComboBox2.getSelectedItem().toString()
                    + ":"
                    + jComboBox3.getSelectedItem().toString()
                    + " "
                    + jComboBox4.getSelectedItem().toString();

            int numHabitacion =

                Integer.parseInt(

                        jComboBox5.getSelectedItem().toString()

                    );

            Cita cita = new Cita(
                    0,
                    idPaciente,
                    idMedico,
                    fechaCita,
                    horaCita,
                    numHabitacion

            );

            CitaDAO citaDAO = new CitaDAO();
            boolean insertada = citaDAO.insertar(cita);
            citaDAO.cerrarConexion();
            
           
            if (insertada) {
                JOptionPane.showMessageDialog(
                    this, "Cita agregada correctamente."
                );

                dispose();

            } else {

                JOptionPane.showMessageDialog(
                        this, "No fue posible agregar la cita.", "Error",
                        JOptionPane.ERROR_MESSAGE
                );

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE

            );
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogAnadirCita dialog = new DialogAnadirCita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
