package vista;


import controlador.MedicoDAO;
import controlador.PacienteDAO;
import intefaces.ValidadorPaciente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelo.Medico;
import modelo.Paciente;
import validaciones.ValidadorPacienteImpl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class DialogModificarPaciente extends javax.swing.JDialog {
    
    private Paciente paciente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogModificarPaciente.class.getName());

    /**
     * Creates new form DialogAnadirMedico
     */
    public DialogModificarPaciente(java.awt.Frame parent, boolean modal, Paciente paciente) {

        super(parent, modal);
        this.paciente = paciente;
        initComponents();
        setSize(400, 350);
        setTitle("Modificar Paciente");
        setResizable(false);
        setLocationRelativeTo(parent);

        try {

            MaskFormatter maskTel = new MaskFormatter("### - ### - ####");
            maskTel.setPlaceholderCharacter('0');
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(maskTel));

        } catch (java.text.ParseException e) {

            e.printStackTrace();

        }
        
        try {

            MaskFormatter maskFecha = new MaskFormatter("##-##-####");

            maskFecha.setPlaceholderCharacter('_');

            jFormattedTextField3.setFormatterFactory(
            new javax.swing.text.DefaultFormatterFactory(maskFecha)
            );

        } catch (java.text.ParseException e) {

        e.printStackTrace();

}

        cargarCombos();

        cargarDatosPaciente();

    }
    
    
    private void cargarCombos() {

        jComboBox2.removeAllItems();
        jComboBox2.addItem("M");
        jComboBox2.addItem("F");
        jComboBox3.removeAllItems();
        jComboBox3.addItem("Soltero");
        jComboBox3.addItem("Casado");
        jComboBox3.addItem("Divorciado");    
        jComboBox3.addItem("Viudo");
        jComboBox4.removeAllItems();

        MedicoDAO medicoDAO = new MedicoDAO();

        List<Medico> medicos = medicoDAO.obtenerTodos();

        for (Medico medico : medicos) {

            jComboBox4.addItem(

                    medico.getIdMedico()       
                    + " - "
                    + medico.getNombre()
                    + " "
                    + medico.getApellido()
            );

        }

    }
    
    private void cargarDatosPaciente() {

        if (paciente == null) {
            return;
        }

        jTextField1.setText(paciente.getNombre());
        jTextField2.setText(paciente.getApellido());
        
        jFormattedTextField2.setText(paciente.getTelefono());

        jFormattedTextField3.setText(paciente.getFechaNacimiento());

        jComboBox2.setSelectedItem(paciente.getSexo());

        jComboBox3.setSelectedItem(paciente.getEstadoCivil());

        for (int i = 0; i < jComboBox4.getItemCount(); i++) {

            String item = jComboBox4.getItemAt(i);

            if (item.startsWith(
                    String.valueOf(
                            paciente.getIdMedico()
                    )
            )) {
                jComboBox4.setSelectedIndex(i);
                break;

            }

        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 60, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 30, 260, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 70, 260, 30);

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(100, 110, 260, 30);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 280, 270, 23);

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 60, 17);

        jLabel6.setText("Teléfono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 120, 70, 17);

        jLabel7.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 160, 140, 17);
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(160, 150, 200, 30);

        jLabel8.setText("Sexo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 200, 29, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(70, 200, 72, 23);

        jLabel9.setText("Estado Civil");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 200, 80, 17);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(250, 200, 110, 23);

        jLabel10.setText("ID Médico");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 240, 70, 17);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(90, 240, 250, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = jTextField1.getText().trim();
        String apellido = jTextField2.getText().trim();
        String telefono = jFormattedTextField2.getText().trim();
        String fechaNacimiento = jFormattedTextField3.getText().trim();
        String sexo = jComboBox2.getSelectedItem().toString();
        String estadoCivil = jComboBox3.getSelectedItem().toString();
        String medicoSeleccionado = jComboBox4.getSelectedItem().toString();

        int idMedico = Integer.parseInt(medicoSeleccionado.split(" - ")[0]);

        if (nombre.isEmpty() || apellido.isEmpty() || fechaNacimiento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;

        }

        paciente.setNombre(nombre);
        paciente.setApellido(apellido);
        paciente.setTelefono(telefono);
        paciente.setFechaNacimiento(fechaNacimiento);
        paciente.setSexo(sexo);
        paciente.setEstadoCivil(estadoCivil);
        paciente.setIdMedico(idMedico);
        
        try {

            ValidadorPaciente validador = new ValidadorPacienteImpl();

            validador.validar(paciente);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;

    }

        PacienteDAO dao = new PacienteDAO();
    
        if (dao.actualizar(paciente)) {
            JOptionPane.showMessageDialog(this, "Paciente modificado correctamente.");

            dispose();

        } else {

            JOptionPane.showMessageDialog(this, "No fue posible modificar el paciente.");

        }

        dao.cerrarConexion();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
