package vista;


import controlador.MedicoDAO;
import intefaces.ValidadorMedico;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelo.Medico;
import validaciones.ValidadorMedicoImpl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author josesanchez
 */
public class DialogAnadirMedico extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAnadirMedico.class.getName());

    /**
     * Creates new form DialogAnadirMedico
     */
    public DialogAnadirMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(400, 350);
        setTitle("Añadir Medico");
        setResizable(false);
        setLocationRelativeTo(parent);
        
         try {
            MaskFormatter maskId = new MaskFormatter("####");
            maskId.setPlaceholderCharacter('0');
            jFormattedTextField1.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(maskId)
            );
      
        } catch (java.text.ParseException e) {
        e.printStackTrace();
        }
        
        try {
            MaskFormatter maskTel = new MaskFormatter("### - ### - ####");
            maskTel.setPlaceholderCharacter('0');
            jFormattedTextField2.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(maskTel)
            );
            
        } catch (java.text.ParseException e){
            e.printStackTrace();
        }
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        jLabel1.setText("ID Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 70, 17);

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(100, 20, 260, 30);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 60, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 60, 260, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 100, 260, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(100, 180, 260, 30);

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(100, 220, 260, 30);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 270, 210, 23);

        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 60, 17);

        jLabel4.setText("Núm Dep.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 60, 17);

        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 60, 17);

        jLabel6.setText("Teléfono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 70, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(100, 140, 260, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        insertarMedico(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogAnadirMedico dialog = new DialogAnadirMedico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void insertarMedico() {

        try {
            int idMedico = Integer.parseInt(jFormattedTextField1.getText().trim());
            
            String nombre = jTextField1.getText().trim();
            
            String apellido = jTextField2.getText().trim();
            
            int numeroDepartamento = Integer.parseInt(
                    jComboBox1.getSelectedItem().toString()
            );
            
            String direccion = jTextField4.getText().trim();
            
            String telefono = jFormattedTextField2.getText().trim();
            
            Medico medico = new Medico(
                    idMedico,
                    nombre,
                    apellido,
                    numeroDepartamento,
                    direccion,
                    telefono
            );
            
            MedicoDAO medicoDAO = new MedicoDAO();
            
            ValidadorMedico validador =
                    new ValidadorMedicoImpl();
            
            validador.validar(medico);
            
            boolean insertado = medicoDAO.insertar(medico);
            
            if (insertado) {
                
                JOptionPane.showMessageDialog(
                        this,
                        "Médico agregado correctamente."
                );
                System.out.print("se agrego un medico");
                
                dispose();
                
            } else {
                
                JOptionPane.showMessageDialog(
                        this,
                        "No fue posible agregar el médico."
                );
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validación", JOptionPane.WARNING_MESSAGE);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
