/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.VistaParticionDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.VistaParticion;

/**
 *
 * @author josesanchez
 */
public class DialogVistaParticion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogVistaParticion.class.getName());

    /**
     * Creates new form DialogVistaParticion
     */
    public DialogVistaParticion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(900, 500);
        setLocationRelativeTo(parent);
        
        cargarTabla();
    }
    
    private void cargarTabla() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("No.");
        modelo.addColumn("Paciente");
        modelo.addColumn("Medico");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Habitacion");
        modelo.addColumn("Tipo");

        VistaParticionDAO dao = new VistaParticionDAO();

        List<VistaParticion> lista = dao.obtenerTodos();

        for (VistaParticion vista : lista) {

            modelo.addRow(new Object[] {

                vista.getNumCita(),
                vista.getIdPaciente(),
                vista.getIdMedico(),
                vista.getFechaCita(),
                vista.getHoraCita(),
                vista.getNumHabitacion(),
                vista.getTipo()

            });

        }

        dao.cerrarConexion();

        jTable1.setModel(modelo);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 880, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
