/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.VistaCitaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import modelo.VistaCita;

/**
 *
 * @author josesanchez
 */
public class DialogVistaCitas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogVistaCitas.class.getName());

    /**
     * Creates new form DialogVistaCitas
     */
    public DialogVistaCitas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {

            MaskFormatter maskFecha = new MaskFormatter("##-##-####");

            maskFecha.setPlaceholderCharacter('0');

            jFormattedTextField1.setFormatterFactory(

                    new javax.swing.text.DefaultFormatterFactory(maskFecha)

            );

        } catch (Exception e) {

            e.printStackTrace();

        }
        
    }
    
    private void cargarTabla() {

        String fecha = jFormattedTextField1.getText().trim();
        
        if (fecha.equals("00-00-0000")) {

            JOptionPane.showMessageDialog(this, "Ingrese una fecha!", "Campo Vacío", JOptionPane.WARNING_MESSAGE);

            return;

        }

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Paciente");
        modelo.addColumn("Médico");

        VistaCitaDAO dao = new VistaCitaDAO();

        List<VistaCita> lista = dao.buscarPorFecha(fecha);
        
        if (lista.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No hay citas programadas para esa fecha.", "Consulta de citas", JOptionPane.INFORMATION_MESSAGE

            );

            dao.cerrarConexion();

            jTable1.setModel(modelo);

            return;

        }

        for (VistaCita vista : lista) {

            modelo.addRow(new Object[] {

                vista.getFechaCita(),

                vista.getHoraCita(),

                vista.getNombrePaciente(),

                vista.getNombreMedico()

            });
        
        }
    
        dao.cerrarConexion();

        jTable1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("Fecha de cita:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 90, 17);
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(140, 20, 180, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Paciente", "Médico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 430, 360);

        jButton1.setText("Consutlar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 20, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargarTabla(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
