/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import controlador.CitaDAO;
import controlador.PacienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelo.Cita;
import modelo.Paciente;

/**
 *
 * @author josesanchez
 */
public class DialogModificarCita extends javax.swing.JDialog {
    
    private List<Paciente> listaPacientes;

    private Cita cita;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogModificarCita.class.getName());

    /**
     * Creates new form DialogModificarCita
     */
    public DialogModificarCita(java.awt.Frame parent, boolean modal, Cita cita) {

        super(parent, modal);

        initComponents();

        this.cita = cita;

        setSize(400, 320);

        setResizable(false);

        setLocationRelativeTo(parent);

        cargarPacientes();

        try {

            MaskFormatter maskFecha = new MaskFormatter("##-##-####");

            maskFecha.setPlaceholderCharacter('0');

            jFormattedTextField1.setFormatterFactory(

                    new javax.swing.text.DefaultFormatterFactory(maskFecha)

            );

        } catch (Exception e) {

            e.printStackTrace();

        }

        cargarDatos();

    }
    
    private void cargarPacientes() {

        PacienteDAO pacienteDAO = new PacienteDAO();

        listaPacientes = pacienteDAO.obtenerTodos();

        jComboBox1.removeAllItems();

        for (Paciente paciente : listaPacientes) {

            jComboBox1.addItem(
                    paciente.getIdPaciente()
                    + " - "
                    + paciente.getNombre()
                    + " "
                    + paciente.getApellido()
            );

        }

        pacienteDAO.cerrarConexion();

    }
    
    private void cargarDatos() {

        for (int i = 0; i < listaPacientes.size(); i++) {

            if (listaPacientes.get(i).getIdPaciente() == cita.getIdPaciente()) {

                jComboBox1.setSelectedIndex(i);

                break;

            }

        }

        jFormattedTextField1.setText(cita.getFechaCita());

        String horaCompleta = cita.getHoraCita();

        String[] partes = horaCompleta.split(" ");

        String horaMinuto = partes[0];

        String ampm = partes[1];

        String[] hm = horaMinuto.split(":");

        jComboBox2.setSelectedItem(hm[0]);

        jComboBox3.setSelectedItem(hm[1]);

        jComboBox4.setSelectedItem(ampm);

        jComboBox5.setSelectedItem(
            String.valueOf(cita.getNumHabitacion())
        );

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Paciente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 70, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(100, 30, 260, 30);

        jLabel2.setText("Fecha de la cita ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 97, 17);

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(150, 70, 210, 30);

        jLabel3.setText("Hora cita");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 80, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(100, 120, 70, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(190, 120, 70, 23);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a.m.", "p.m." }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(280, 120, 80, 23);

        jLabel4.setText("Num Habitación");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 110, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(140, 160, 220, 23);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 210, 290, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            int indicePaciente = jComboBox1.getSelectedIndex();

            if (indicePaciente < 0) {

                JOptionPane.showMessageDialog(this, "Seleccione un paciente.", "Validación", JOptionPane.WARNING_MESSAGE);
                return;

            }

            Paciente paciente = listaPacientes.get(indicePaciente);
            
            cita.setIdPaciente(
                    paciente.getIdPaciente()
            );

            cita.setIdMedico(
                    paciente.getIdMedico()
            );

            cita.setFechaCita(
                    jFormattedTextField1.getText().trim()
            );

            String horaCita = jComboBox2.getSelectedItem().toString() + ":" + jComboBox3.getSelectedItem().toString()
                    + " " + jComboBox4.getSelectedItem().toString();

            cita.setHoraCita(horaCita);

            cita.setNumHabitacion(Integer.parseInt( jComboBox5.getSelectedItem().toString()));

            CitaDAO citaDAO = new CitaDAO();

            boolean actualizada =

                    citaDAO.actualizar(cita);

            citaDAO.cerrarConexion();

            if (actualizada) {

                JOptionPane.showMessageDialog(

                        this,

                        "Cita modificada correctamente."

                );

                dispose();

            } else {

                JOptionPane.showMessageDialog(

                        this,

                        "No fue posible modificar la cita.",

                        "Error",

                        JOptionPane.ERROR_MESSAGE

                );

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(

                    this,

                    e.getMessage(),

                    "Error",

                    JOptionPane.ERROR_MESSAGE

            );

        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
