/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author josesanchez
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private static final String HASH_ADMIN = "a7177c8f1132f5f7ebf3637a727ca49757be5dd6f1719d86f293c78b8f753736";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        setLocationRelativeTo(null); 
    }
    
    private boolean validarAdministrador() {

        javax.swing.JPasswordField campo = new javax.swing.JPasswordField();

        int opcion = javax.swing.JOptionPane.showConfirmDialog(this, campo, "Contraseña Administrador", javax.swing.JOptionPane.OK_CANCEL_OPTION);

        if (opcion != javax.swing.JOptionPane.OK_OPTION) {

            return false;

        }

        String password = new String(campo.getPassword());

        String hashIngresado = Seguridad.Seguridad.encriptarSHA256(password);

        return HASH_ADMIN.equals(hashIngresado);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 20, 25));
        setBounds(new java.awt.Rectangle(0, 31, 400, 450));
        setMinimumSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 200, 200);

        jComboBox1.setBackground(new java.awt.Color(40, 81, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Guest" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(40, 230, 310, 40);

        jButton1.setBackground(new java.awt.Color(40, 81, 102));
        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 290, 310, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String rol = jComboBox1.getSelectedItem().toString();

        if (rol.equals("Guest")) {

        Inicio2 ventana = new Inicio2();
        ventana.setVisible(true);
        dispose();

        return;

        }
        
        if (rol.equals("Administrador")) {

            if (validarAdministrador()) {
                
                Inicio ventana = new Inicio();
                ventana.setVisible(true);
                dispose();

            } else {

                javax.swing.JOptionPane.showMessageDialog(

                    this,

                    "Contraseña incorrecta"
                );
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
